name: Prepare tag
on:
  push:
    branches: [ main ]
jobs:
  prepare-release:
    if: github.actor != 'YOUR_TECH_ACCOUNT_HERE'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.TOKEN_TECH }}
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          server-id: github
          cache: 'maven'
      - name: Prepare and tag
        run: |
          git config user.name YOUR_USERNAME_HERE
          git config user.email YOUR_EMAIL_HERE
          
          mvn -V -B release:prepare -DtagNameFormat=@{project.version} -Darguments=-DskipTests -DpushChanges=false
          mvn -V -B release:clean
          
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TECH }}